### ISSUE TITLE
ModuleNotFoundError: No module named ...

### ISSUE THREAD

**Issue by dsonhoang** [rkbennett/od_import#10]
I tried running the sample code and got this error:

**Traceback (most recent call last):
  File "", line 5, in <module>
    import py3memimporter
ModuleNotFoundError: No module named 'py3memimporter'**

The full code is: 

**import od_import**

**config={"type": "git", "git": "github", "user": "rkbennett", "repo": "py3memimporter"}
with od_import.remote_source('https://github.com', config=config):
  import py3memimporter**

**Comment by rkbennett** [comment]
Sorry I didn't see this, what version of python are you running?

**Comment by rkbennett** [comment]
I'm going to go ahead and close this, feel free to open another issue if that doesn't solve it.
