### ISSUE TITLE
Does not work on many version of Python

### ISSUE THREAD

**Issue by RyanHope** [rkbennett/od_import#11]
I can't get this to work on any version of python that I try, 3.8 32bit, 3.10 64bit, 3.11 32bit and 64bit.

What can I do to help debug this?

**Comment by rkbennett** [comment]
3.8 may not work, but it has been tested with 3.10-3.12, what are you trying to import?

**Comment by RyanHope** [comment]
I did a 'pip install git+<your repo>'. I am trying to load a pure python package that I made that I use in a few of my programs.  I built the pacakge with 'python -m build'. I using od_import.remote_source on the generated wheel and the tar.gz. After I fixed the user-agent issue, it seems like the files are getting downloaded and processed, but there are no errors and my import fails.

**Comment by rkbennett** [comment]
So are you using something like

```python
with od_import.remote_source(.....):
  import mymodule
```

**Comment by RyanHope** [comment]
I just made the most minimal test package and this is how I am testing it...

```
import od_import

config = {"headers": {'User-Agent': 'Mozilla/5.0'}}
with od_import.remote_source("https://mcuinnovations.com/media/simple-0.0.0.tar.gz", config=config):
    import simple
    print(simple.simple())
```

**Comment by rkbennett** [comment]
Is there an error?

**Comment by RyanHope** [comment]
```
Traceback (most recent call last):
  File "test4.py", line 5, in <module>
    import simple
ModuleNotFoundError: No module named 'simple'
```

**Comment by RyanHope** [comment]
This link works if you want to view the content: https://mcuinnovations.com/media/simple-0.0.0.tar.gz

```
simple-0.0.0:
total 0
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 .
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 ..
-rwxrwxrwx 1 ryan ryan  53 Jun 22 10:50 PKG-INFO
-rwxrwxrwx 1 ryan ryan  51 Jun 22 10:50 pyproject.toml
-rwxrwxrwx 1 ryan ryan  42 Jun 22 10:50 setup.cfg
-rwxrwxrwx 1 ryan ryan  39 Jun 22 10:45 setup.py
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 simple
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 simple.egg-info

simple-0.0.0/simple:
total 0
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 .
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 ..
-rwxrwxrwx 1 ryan ryan  45 Jun 22 10:44 __init__.py

simple-0.0.0/simple.egg-info:
total 0
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 .
drwxrwxrwx 1 ryan ryan 512 Jun 22 13:25 ..
-rwxrwxrwx 1 ryan ryan  53 Jun 22 10:50 PKG-INFO
-rwxrwxrwx 1 ryan ryan 162 Jun 22 10:50 SOURCES.txt
-rwxrwxrwx 1 ryan ryan   1 Jun 22 10:50 dependency_links.txt
-rwxrwxrwx 1 ryan ryan   7 Jun 22 10:50 top_level.txt
```

**Comment by rkbennett** [comment]
Okay, so the reason this is happening is because the packages need to be directly under the tar. So if you move the simple directory to the current level that simple-0.0.0 currently is.

**Comment by RyanHope** [comment]
Progress! So this did work with a manually packed zip file, but it doesn't work with a wheel that has the same directory structure as the manually created zip (although file contents are not 100% the same). Would be nice to be able to use this with files as produced by the standard build tools.

**Comment by RyanHope** [comment]
Just a little digging into why wheels dont work out the box... so even though the archives looks "the same" when using something like 7z to inspect, the actual archives are slightly different. I added some print outputs to od_import...

```
(.venv-ecuwb) PS > python .\test4.py https://mcuinnovations.com/media/simple-0.0.0-py3-none-any.whl
https://mcuinnovations.com/media/simple-0.0.0-py3-none-any.whl
['simple/__init__.py', 'simple-0.0.0.dist-info/METADATA', 'simple-0.0.0.dist-info/WHEEL', 'simple-0.0.0.dist-info/top_level.txt', 'simple-0.0.0.dist-info/RECORD']
Traceback (most recent call last):
  File "test4.py", line 15, in <module>
    main(args)
  File "test4.py", line 8, in main
    import simple
ModuleNotFoundError: No module named 'simple'
(.venv-ecuwb) PS > python .\test4.py https://mcuinnovations.com/media/simple-0.0.0.zip
https://mcuinnovations.com/media/simple-0.0.0.zip
['PKG-INFO', 'pyproject.toml', 'setup.cfg', 'setup.py', 'simple/', 'simple/__init__.py', 'simple.egg-info/', 'simple.egg-info/dependency_links.txt', 'simple.egg-info/PKG-INFO', 'simple.egg-info/SOURCES.txt', 'simple.egg-info/top_level.txt']
Hello from simple
None
```

**Comment by RyanHope** [comment]
Adding the code below to ziph.__init__ "fixes" loading wheels (I know its ugly, first cut)...

```
dirs = []
        for i in range(len(self.path_cache)):
            dir = os.path.dirname(self.path_cache[i]) + "/"
            if dir not in dirs and dir not in self.path_cache:
                dirs.append(dir)
        self.path_cache += dirs
```

**Comment by rkbennett** [comment]
How are you generating that whl file? When I do a `pip download` the folder structure doesn't nest like that on a couple of the packages I've tested with.

**Comment by RyanHope** [comment]
```
pip install wheel
```

**Comment by rkbennett** [comment]
I was under the impression that whl files are built by running `python setup.py bdist_wheel`. When built this way the contents of the wheel file don't get nested in the way that you are seeing. This also lines up to the folder structure I've seen when `pip download`ing whl files.

**Comment by RyanHope** [comment]
Using ``python setup.py`` to build distributables like this I think is discouraged these days. I saw pip complaining about my usage of it recently so I switched to the ``build`` package which it recommended.

**Comment by rkbennett** [comment]
Hmm, even building packages with `python -m build` results in the directory structure I'd expect to see.

**Comment by rkbennett** [comment]
The only thing structured like that is sdist

**Comment by rkbennett** [comment]
I'm going to go ahead and close this as transparent handling of versioned sdist folders was added in 9175627
