### ISSUE TITLE
urllib.request.Request http.client.IncompleteRead error

### ISSUE THREAD

**Issue by boludoz** [rkbennett/od_import#4]
```
[Running] python -u "c:\Users\franc\Downloads\undetected-chromedriver-master\undetected_chromedriver\import http.py"
Traceback (most recent call last):
  File "c:\Users\franc\Downloads\undetected-chromedriver-master\undetected_chromedriver\import http.py", line 24, in <module>
    download_file('https://github.com/boludoz/jubilant-umbrella/blob/main/seleniumbase_.zip?raw=True')
  File "c:\Users\franc\Downloads\undetected-chromedriver-master\undetected_chromedriver\import http.py", line 10, in download_file
    return_raw = response.read()
                 ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\http\client.py", line 488, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\http\client.py", line 635, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(16495232 bytes read, 1164128 more expected)

```

**Comment by boludoz** [comment]
After several attempts I managed to catch a similar error.

**Comment by boludoz** [comment]
It seems to be an error of old servers or Microsoft servers that close the session before the download is finished.

**Comment by rkbennett** [comment]
So I've added the ability to downgrade http versions, can you try adding `"http_version": "1.0"` to your config dict?

**Comment by boludoz** [comment]
> So I've added the ability to downgrade http versions, can you try adding `"http_version": "1.0"` to your config dict?

The problem is that if the server does not accept this protocol we will be rejected.

**Comment by rkbennett** [comment]
Have you tried it against the server you're talking about though?

**Comment by boludoz** [comment]
> Have you tried it against the server you're talking about though?

I'm testing it in github raw zip.

**Comment by boludoz** [comment]
Will it be possible to continue the download from the last byte?

**Comment by boludoz** [comment]
For example: https://github.com/rkbennett/od_import/blob/main/od_import_stg.py?raw=True

**Comment by boludoz** [comment]
> Will it be possible to continue the download from the last byte?

from http.client import IncompleteRead
from http.client import HTTPConnection
import urllib.request

def download_file(request, unsafe=False):
    bytes_ranges_supported = False
    http_1_0_tolerate = False
    return_unsafe = False
    
    return_raw = b''

    # Check if is supported bytes ranges
    try:
        with urllib.request.urlopen(request) as response:
            if response.headers.get('Accept-Ranges') == 'bytes':
                bytes_ranges_supported = True
    except:
        pass
    
    # Check if is supported HTTP/1.0
    try:
        request.add_header('Range', 'bytes=0-')
        with urllib.request.urlopen(request) as response:
            if response.status == 206:
                http_1_0_tolerate = True
    except:
        pass
    
    # Unsafe mode
    if bytes_ranges_supported:
        while True:
            try:
                request.add_header('Range', 'bytes=%d-' % len(return_raw))
                with urllib.request.urlopen(request) as response:
                    return_raw += response.read()
                    return return_raw
            except IncompleteRead as e:
                return_raw += e.partial
                
    # Alternative mode
    elif http_1_0_tolerate:
        HTTPConnection._http_vsn = 10
        HTTPConnection._http_vsn_str = 'HTTP/1.0'

    # Unsafe mode
    elif unsafe:
        return_unsafe = True
        
    # Legacy mode
    if return_raw == b'':
        with urllib.request.urlopen(request) as response:
            try:
                return_raw = response.read()
            except IncompleteRead as e:
                if return_unsafe:
                    return_raw = e.partial
                else:
                    raise e

    return return_raw

url = 'https://github.com/boludoz/jubilant-umbrella/blob/main/seleniumbase_.zip?raw=True'
req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'})

with open('seleniumbase_.zip', 'wb') as f:
    f.write(download_file(req))

This function tries to do everything possible to download, and checked the files with hex and they are correct.

**Comment by boludoz** [comment]
from http.client import IncompleteRead
from http.client import HTTPConnection
import urllib.request
import time
def download_file(request, unsafe=False, max_retries=15):
    bytes_ranges_supported = False
    http_1_0_tolerate = False
    return_unsafe = False
    
    return_raw = b''

    # Check if is supported bytes ranges
    try:
        with urllib.request.urlopen(request) as response:
            if response.headers.get('Accept-Ranges') == 'bytes':
                bytes_ranges_supported = True
    except:
        pass
    
    # Check if is tolerated HTTP/1.0
    if bytes_ranges_supported == False:
        backup_vsn = HTTPConnection._http_vsn
        backup_vsn_str = HTTPConnection._http_vsn_str
        
        try:
            HTTPConnection._http_vsn = 10
            HTTPConnection._http_vsn_str = 'HTTP/1.0'
            with urllib.request.urlopen(request) as response:
                if response.status == 200:
                    http_1_0_tolerate = True
        except:
            pass

    
        if http_1_0_tolerate == False:
            HTTPConnection._http_vsn = backup_vsn
            HTTPConnection._http_vsn_str = backup_vsn_str
     
    # Check features
    any_feature = bytes_ranges_supported or http_1_0_tolerate
    return_unsafe = unsafe and any_feature
    
    # print ('bytes_ranges_supported: %s' % bytes_ranges_supported) # For example, Google doesn't support bytes ranges
    # print ('http_1_0_tolerate: %s' % http_1_0_tolerate)
        
    i = max_retries
    while (i > 0):
        i -= 1
        try:
            if bytes_ranges_supported:
                request.add_header('Range', 'bytes=%d-' % len(return_raw))
            with urllib.request.urlopen(request) as response:
                if bytes_ranges_supported:
                    return_raw += response.read()
                    i = 0
                else:
                    return_raw = response.read()
        except IncompleteRead as e:
            if bytes_ranges_supported == False:
                return_raw = e.partial
                if return_unsafe and i == 0:
                    return return_raw
                elif i == 0:
                    raise e
            else:
                return_raw += e.partial
        finally:
            if bytes_ranges_supported == False:
                break
            try:
                time.sleep(0.10)
            except OSError:
                break
            except KeyboardInterrupt:
                raise
                                         
    return return_raw

url = 'https://github.com/boludoz/jubilant-umbrella/blob/main/seleniumbase_.zip?raw=True'
req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'})

with open('seleniumbase_.zip', 'wb') as f:
    f.write(download_file(req))

**Comment by rkbennett** [comment]
Can you paste the actual code you're running which is using od_import as well as the error that's being raised along with any warnings od_import is outputs?

**Comment by boludoz** [comment]
Yes of course, I am using your original code, it does not make any changes and I will try to demonstrate this error.

**Comment by boludoz** [comment]
> Can you paste the actual code you're running which is using od_import as well as the error that's being raised along with any warnings od_import outputs?

`WARNING:root:[!] memory imports not loaded, some packages may not work
Traceback (most recent call last):
  File "C:\Users\franc\Downloads\undetected-chromedriver-master\Nueva carpeta\Untitled-4.py", line 3, in <module>
    with od_import.remote_source('https://github.com/boludoz/jubilant-umbrella/blob/main/seleniumbase_.zip?raw=True'):
  File "C:\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\franc\Downloads\undetected-chromedriver-master\Nueva carpeta\od_import\__init__.py", line 762, in remote_source
    import_hook = add_remote_source(url, INSECURE=INSECURE, return_importer=True, zip_password=zip_password, config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\Downloads\undetected-chromedriver-master\Nueva carpeta\od_import\__init__.py", line 572, in add_remote_source
    importer = ODImporter(url, INSECURE, zip_password=zip_password, config=config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\Downloads\undetected-chromedriver-master\Nueva carpeta\od_import\__init__.py", line 188, in __init__
    archive_handler = archive_handlers['zip']()(resp, self.url, self.path_cache, pwd=self.zip_password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\Downloads\undetected-chromedriver-master\Nueva carpeta\od_import\__init__.py", line 87, in zip_handler
    from .archive_providers import ziph
ModuleNotFoundError: No module named 'od_import.archive_providers'`

**Comment by rkbennett** [comment]
That's not the error you're saying you've been having though. There's no IncompleteRead error there?

**Comment by boludoz** [comment]
> That's not the error you're saying you've been having though. There's no IncompleteRead error there?

It's okay to forget it, I will be aware of every update you make and I will modify the code so that it works for me.

**Comment by rkbennett** [comment]
@boludoz Can you try generating that error again now that the archive_provider submodule has an __init__ which is what I assume was causing your previous error?

**Comment by boludoz** [comment]
> @boludoz Can you try generating that error again now that the archive_provider submodule has an which is what I assume was causing your previous error?`__init__`
> 
> I also added a option that can be passed as an or to the config dict. If you also would want to give that a try with setting a higher timeout threshold that might give us some more information to work with.`timeout``int``float`

Exactly, the lack of __init__ generates the error, that's why I added it.

**Comment by boludoz** [comment]
> @boludoz Can you try generating that error again now that the archive_provider submodule has an which is what I assume was causing your previous error?`__init__`
> 
> I also added a option that can be passed as an or to the config dict. If you also would want to give that a try with setting a higher timeout threshold that might give us some more information to work with.`timeout``int``float`

I recommend not adding timeout, that does not solve the problem. The problem is on the server.

**Comment by rkbennett** [comment]
If you look at the bottom of the od_import.protocol_handlers.http._core, the http version get's reset after each request the modifies it, so nothing persists

**Comment by boludoz** [comment]
> If you look at the bottom of the od_import.protocol_handlers.http._core, the http version gets reset after each request that modifies it, so nothing persists

Explained in #6 

Please keep in mind that I do what I do because I love scripting, I do not intend to offend you at any time and what you have done is genius.

**Comment by rkbennett** [comment]
I'm going to go ahead and reopen this so I can track it. I've now been able to write a python base server that can force this error so I can replicate it.

**Comment by boludoz** [comment]
> I'm going to go ahead and reopen this so I can track it. I've now been able to write a python based server that can force this error so I can replicate it.

Tomorrow I promise to test it from my laptop with a wireless connection. Remember that the example shown is a simulation of the error, but it had happened to me previously.
