### ISSUE TITLE
Suggestion: add support for physical zip files taking advantage of ZipImport being deprecated and debug questions

### ISSUE THREAD

**Issue by boludoz** [rkbennett/od_import#7]
```
import od_import

with od_import.remote_source(r'file://C:\Users\franc\Downloads\seleniumbase_.zip'):
    from seleniumbase import *
```

**Comment by boludoz** [comment]
Another thing that comes to mind is if it is capable of handling files that are inside the packages? If it does, it is even more incredible.

**Comment by rkbennett** [comment]
So far as I know, as long as the package doesn't require dynamic patching to run (pycrypto, pycryptodome, pyclr, etc) then they should just work. The only other exception I can think of is python files that were compiled with something like cython, I don't support those.

**Comment by rkbennett** [comment]
Here's what I got testing your example
![image](https://github.com/rkbennett/od_import/assets/44292326/12ef2bc8-8eb7-48fb-9781-829cabea0cbd)

**Comment by boludoz** [comment]
added

**Comment by rkbennett** [comment]
Are we good to close this issue?

**Comment by boludoz** [comment]
> Are we good to close this issue?

Yes, because I already added the feature to add files, all that remains is to do the pull request.

**Comment by rkbennett** [comment]
I don't know why I hadn't thought about this in the past, but urllib *can* open files already. I did a quick tweak to the code to allow file path urls to be passed, so for example:

<img width="819" height="180" alt="Image" src="https://github.com/user-attachments/assets/2843a3e8-c293-46b6-a71c-89fc7c377ccc" />
