### ISSUE TITLE
[BUG] Importing zip repo

### ISSUE THREAD

**Issue by boludoz** [rkbennett/od_import#9]
```
  File "c:\Users\Admin\Downloads\infonet\final\main.py", line 8, in <module>
    with od_import.github(user="boludoz", repo="....", branch="main", git_type="git_zip", api_key="github_pat_11ACY...."):      
  File "C:\Program Files\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 642, in github
    import_hook = add_remote_source("https://github.com", return_importer=True, config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 585, in add_remote_source
    importer = ODImporter(url, INSECURE, zip_password=zip_password, config=config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 197, in __init__
    resp = self.proto_handler(self.url, path_cache=self.path_cache, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\protocol_handlers\http\__init__.py", line 54, in http
    return helper(url, path, path_cache, cache_update, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\protocol_handlers\http\git_zip.py", line 35, in git_zip
    config.headers["Authorization"] = f"Bearer {config.api_key}" if config.git == "github" else f"token {config.api_key}"
    ^^^^^^^^^^^^^^
AttributeError: 'imp_config' object has no attribute 'headers'
```

**Comment by boludoz** [comment]
`od_import.github(user="boludoz", repo="....", branch="main", git_type="git_zip", api_key="github_pat_11ACY...."):`

**Comment by rkbennett** [comment]
This bug should be fixed with the latest commit, feel free to try it and let me know.

**Comment by rkbennett** [comment]
This also impacted git_type of `git` when using PATs, this is was also fixed on the subsequent commit

**Comment by boludoz** [comment]
zip with password does not work either

**Comment by boludoz** [comment]
File "C:\Program Files\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 642, in github
    import_hook = add_remote_source("https://github.com", return_importer=True, config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 585, in add_remote_source
    importer = ODImporter(url, INSECURE, zip_password=zip_password, path_cache=path_cache, config=config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\__init__.py", line 197, in __init__
    resp = self.proto_handler(self.url, path_cache=self.path_cache, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\protocol_handlers\http\__init__.py", line 54, in http
    return helper(url, path, path_cache, cache_update, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Downloads\infonet\final\od_import\protocol_handlers\http\git_zip.py", line 35, in git_zip
    config.headers["Authorization"] = f"Bearer {config.api_key}" if config.git == "github" else f"token {config.api_key}"
    ^^^^^^^^^^^^^^
AttributeError: 'imp_config' object has no attribute 'headers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Downloads\infonet\final\main.py", line 35, in <module>
    traceback.print_exc()
    ^^^^^^^^^
NameError: name 'traceback' is not defined. Did you forget to import 'traceback'

**Comment by boludoz** [comment]
```
import urllib.request

token = 'github_pat_11ACY........'
owner = 'boludoz'
repo = '.......'
url = f'https://api.github.com/repos/{owner}/{repo}/zipball/main'

headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3.raw',
}

req = urllib.request.Request(url, headers=headers)
with urllib.request.urlopen(req) as response:
    data = response.read()

    with open('archivo.zip', 'wb') as f:
        f.write(data)
```

This downloads very quickly, if I download the repo without zip it is much slower. The problem is that I can't access the folder it generates inside.

**Comment by boludoz** [comment]
`with od_import.remote_source('https://my-packages.local/package.zip', zip_password=b"SuperSecretPassword"):
  import zip_package
`
I've tried to do something like that using f'https://api.github.com/repos/{owner}/{repo}/zipball/' and injecting the key_api header but unfortunately I can't get it to work (it can't import the which is inside the folder but does not give an error).

**Comment by boludoz** [comment]
That works for me, but is too slow:
```
config={"api_key":"github_pat_somelongapikeystring", "type": "git_api", "git": "github", "user": "myuser", "repo": "myrepo"}
with od_import.remote_source('https://api.github.com', config=config):
  import py3memimporter
```

**Comment by boludoz** [comment]
It would be good to implement some strategy to access the subfolder in case there is a "badly compressed" zip automatically.

![image](https://github.com/rkbennett/od_import/assets/11653030/8efa12c3-1b77-4398-a7e6-3ec363854082)

**Comment by rkbennett** [comment]
> zip with password does not work either

If this is related to the error you posted below it, yes it is. It was fixed at the same time as the api key. That's because the issue wasn't specific to api keys or passwords, it was related to the zip file.

**Comment by rkbennett** [comment]
> `with od_import.remote_source('https://my-packages.local/package.zip', zip_password=b"SuperSecretPassword"): import zip_package ` I've tried to do something like that using f'[https://api.github.com/repos/{owner}/{repo}/zipball/](https://api.github.com/repos/%7Bowner%7D/%7Brepo%7D/zipball/)' and injecting the key_api header but unfortunately I can't get it to work (it can't import the which is inside the folder but does not give an error).

This is because you're not dealing with a normal filesystem, you're dealing with an api, when od_import searches the provided path, it doesn't exist and therefor can't "find" the module. It then passes to the next meta_hook

**Comment by rkbennett** [comment]
I'm going to close this issue as fixed, as it seems the original headers missing from config issue was fixed. If you are having another issue feel free to create another issue
